# Generated by Django 3.2.16 on 2022-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FilePathField(path='/static/catalogue/images/products'),
        ),
    ]
