# Generated by Django 3.2.16 on 2022-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='flat',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
